### ISSUE TITLE
用示波器截一副生成的sin wave信号的图。

### ISSUE THREAD

**Issue by shanggdlk** [shanggdlk/Lora_backscatter#1]

**Comment by shanggdlk** [comment]
可以放1x4这样的子图。第一幅放sqaure wave，第二幅放经过一阶，第三幅放经过二阶，第四幅放经过三阶。最好可以求一下分别经过着三个RC滤波器之后，RMS是多少。

**Comment by AmandaHuyue** [comment]
[fig_design_decoding_filteredData2.pdf](https://github.com/shanggdlk/Lora_backscatter/files/1319874/fig_design_decoding_filteredData2.pdf)
