### ISSUE TITLE
推导我们的调制方法可以得到完整的LoRa chirp

### ISSUE THREAD

**Issue by shanggdlk** [shanggdlk/Lora_backscatter#3]

**Comment by Lavenderr33** [comment]
取一个基带信号来看，令其带宽为BW。lora的downchirp满足如下条件：在0-BW频率范围内，任一频率有且仅有一点信号与之对应。
    任取BW内某t时刻的信号，设该信号频率为m(0<m<BW)。
    若m<0.5BW ，则在混频后，该点频率变为m+0.5BW，以及m－0.5BW。又因为m<0.5BW ，则m－0.5BW<0，该信号已不在带内。而0<m+0.5BW<BW，故该信号在带内。
    对于上述的m+0.5BW这一频率，其所对应的是原downchirp中t时刻的频率为m+0.5BW的信号，该信号在混频后产生了两个信号，m+0.5BW+0.5BW，以及m+0.5BW－0.5BW。      m+0.5BW+0.5BW=m+BW>BW，故该信号在带外。而m+0.5BW－0.5BW=m，正好等于t时刻信号的原频率，故混频后的upchirp信号满足0-BW频率范围内对于任一频率，有且仅有一点与其对应的关系。
    若m>0.5BW，同理。
