### ISSUE TITLE
描述Packet detection过程

### ISSUE THREAD

**Issue by shanggdlk** [shanggdlk/Lora_backscatter#7]

**Comment by wlJiao** [comment]
## 1、 为什么要检测包？
【原因1】passive tag backscatter的包必须可以被商用的gateway能正确解调，因此，tag产生一个合法的lora包。
【原因2】由于，passive tag直接将自己的信号加载到已经调制了信息的lora包上，所以tag需要将信息加载到包的payload部分，而不能将信息加载到packet的preamble 部分。
因此，tag需要检测incoming lora packet的payload的开始时刻，然后开始加载自己的信息。

## 2、challenges
1. tag检测包要求具有很高的时间精度，因为tag开始调制的时刻需要与原始包payload开始时刻精确地对齐。
2. tag是无源的，能量有限，要求低功耗。
3. 为了提高传输距离，要求tag检测lora信号的灵敏度高。

## 3、传统方法不work
【LoRa协议规定LoRa包格式，图示】在每个packet transmission开始时，gateway会发送一段已知的preamble，用于接收器进行bit 相关操作，实现信号同步和解调。
【传统的接收机】执行相干解调[专利]，需要模拟器件LOC和multiplier，该方法优点是检测精度高，灵敏度高，但是功耗太高。不适合passive tag设计。
【本文的检测方法】为了实现低功耗，避免使用复杂的相关解调电路。但这必然会损失时间精度和接收灵敏度。具体步骤如下：
首先，进行幅度检测，使用低功耗的比较器。
其次，用超低功耗的异或器XOR代替大功耗的multiplier，用本地的低频信号代替LOC的高频信号，让比较器输出的电压信号与本地的低频信号进行异或。

## 4、具体的电路设计

![image](https://user-images.githubusercontent.com/31982814/30517386-e405e4ea-9b8f-11e7-905c-b0f9e3ffb239.png)

1. 带通滤波
这么做的目的：提高接收到信号的信噪比（SNR，signal to noise ratio），提高downlink频段的接收灵敏度。将天线接收的信号进一步进行滤波，将中心频率设置为902MHz，将902MHz带外信号衰减。
带通滤波的实现：RC低通滤波电路和RC高通滤波电路串联，实现带通滤波。
【为什么要选择用RC滤波电路？】RC滤波器是无源滤波器，不需要额外提供电源，降低电路功耗。

2. 信号平均 [参考ambient backscatter]
平均可以减少噪声快速的变化对幅度的影响。如图所示：仿真结果展示。
图1. 200米原始信号的幅度              图2. 平均之后的信号幅度
![image](https://user-images.githubusercontent.com/31982814/30517360-1a2e1e94-9b8f-11e7-81ca-4a2da7734535.png)
![image](https://user-images.githubusercontent.com/31982814/30517361-25fe3ca4-9b8f-11e7-9b19-818eef82d36c.png)

3. 计算阈值 [参考ambient backscatter]
采用RC电路，通过选择合适的电阻和电容的参数值，可以构成一个低通滤波电路。
将变化较快的噪声滤掉，将幅度变化较慢的chirp通过。

4. 比较器模块
比较器的输入信号有两路，一路是信号平均之后的信号，另一路是计算阈值电路的输出信号。
如果原始的平均信号电压大于阈值电压，则比较器输出高电平，表示可能有LoRa packet已经到达。否则，输出低电平，表示无LoRa包。

5. 异或器模块
目的：为了降低噪声带来的检测错误，我们需要检测到连续的8个高电平才能判断LoRa packet的preamble部分结束，可以开始进行调制。
将比较器的输出信号与方波进行异或，检测是否有连续的8个高电平。
如果异或器输出的8个连续的反相方波，则认为可以开始调制。
方波的周期 = 一个chirp的周期 = 0.5119ms
方波频率 f ≈ 2KHz 。
